// packages/vue/src/Traven.vue
<template>
  <div ref="container" class="traven-vue-wrapper"></div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue';
import { TravenEditor } from 'traven';

const props = defineProps({
  defaultValue: { type: String, default: '' },
  options: { type: Object, default: () => ({}) }
});

const emit = defineEmits(['change']);

const container = ref(null);
let editorInstance = null;

onMounted(() => {
  if (!container.value) return;

  editorInstance = new TravenEditor({
    element: container.value,
    initialValue: props.defaultValue,
    onChange: (value) => {
      emit('change', value);
    },
    ...props.options
  });
});

onBeforeUnmount(() => {
  if (editorInstance && typeof editorInstance.destroy === 'function') {
    editorInstance.destroy();
  }
});

// Expose methods to parent
defineExpose({
  getValue: () => editorInstance?.getValue() || '',
  getInstance: () => editorInstance
});
</script>

// packages/svelte/src/lib/Traven.svelte
<!-- packages/svelte/src/Traven.svelte -->
<script>
  import { onMount, onDestroy } from 'svelte';
  import { TravenEditor } from 'traven';

  export let defaultValue = '';
  export let options = {};
  export let onChange = undefined;

  let container;
  let editorInstance;

  export const getValue = () => editorInstance?.getValue() || '';
  export const getInstance = () => editorInstance;

  onMount(() => {
    editorInstance = new TravenEditor({
      element: container,
      initialValue: defaultValue,
      onChange: (newVal) => {
        if (onChange) onChange(newVal);
      },
      ...options
    });
  });

  onDestroy(() => {
    if (editorInstance && typeof editorInstance.destroy === 'function') {
      editorInstance.destroy();
    }
  });
</script>

<div bind:this={container} class="traven-svelte-wrapper"></div>
